# suppress inspection "UnusedProperty"
spring.profiles.active=db
# suppress inspection "UnusedProperty"
logging.level.org.zalando.logbook=TRACE
# suppress inspection "UnusedProperty"
spring.sql.init.mode=always
# suppress inspection "UnusedProperty"
spring.datasource.url=jdbc:h2:file:./db/filmorate
# suppress inspection "UnusedProperty"
spring.datasource.driverClassName=org.h2.Driver
# suppress inspection "UnusedProperty"
spring.datasource.username=sa
# suppress inspection "UnusedProperty"
spring.datasource.password=password
